//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeTable
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimeTable
    {
        public int PeriodEntryId { get; set; }
        public Nullable<int> ClassId { get; set; }
        public string CourseCode { get; set; }
        public Nullable<int> StaffId { get; set; }
        public Nullable<int> PeriodNumber { get; set; }
        public Nullable<int> Day { get; set; }
    
        public virtual Class Class { get; set; }
        public virtual Course Course { get; set; }
        public virtual Staff Staff { get; set; }
    }
}
